### ISSUE TITLE
Fails to install via HACS

### ISSUE THREAD

**Issue by strikeir13** [finity69x2/light-brightness-preset-row#1]
When I try to install this plugin via HACS, it fails. The Home Assistant log gives the following two errors:
`2020-01-12 12:25:39 ERROR (MainThread) [hacs.repository.plugin.finity69x2.light-brightness-preset-row] Repostitory structure not compliant`
`2020-01-12 12:25:39 ERROR (MainThread) [hacs.repository.plugin.finity69x2.light-brightness-preset-row] Download was not complete.`

**Comment by ludeeus** [comment]
https://github.com/finity69x2/light-brightness-preset-row/blob/40ad0a4571509242a4d3ed9ed4a14cbf528e7d52/hacs.json#L3
This should be `false` or not set at all @finity69x2 <https://hacs.xyz/docs/publish/start#hacsjson>

**Comment by finity69x2** [comment]
Sorry about that. I incorrectly followed one of the examples.

Should be fixed now.

**Comment by strikeir13** [comment]
Install works as expected now! Thank you!

**Comment by finity69x2** [comment]
Great! Good to hear.

**Comment by strikeir13** [comment]
Minor thing related to this issue - I think the changes are in the master branch but the 1.0 tag shows up as the most "recent" on HACS. This prompts HACS to think there is an update available to 1.0 when the 1.0 tag has the older file. I think this would be resolved with a 2.0 tag (though I'm no github expert).
