### ISSUE TITLE
Feature request: light with slow transitions

### ISSUE THREAD

**Issue by daniwebCH** [finity69x2/light-brightness-preset-row#11]
Hi,
I think that this would be more a feature request.
I have DALI LEDS controlled via KNX, I have configured the DALI that the transitions are smooth.
I presume that the fact that the transitions are smooth I see as example the following effect:
Scenario:
1) The leds are off
2) I press HIgh
3) I see for some seconds LOW, than it moved to HIGH

I have other LEDS but without a smooth transition and there I do not have this effect.

I could imagine that you are adding a configurable delay before to update the status, on this way we may avoid this effect.
But I do not know if this may be easy to implement as I do not know which kind of functions are available for the plugin.

Thanks

**Comment by finity69x2** [comment]
@daniwebCH 

the only functions are those listed in the readme file.

there is no way to set a delay or transition effect directly in the plugin.

However, I think you might be able to do at least a part of that using a template light and in the template controlling which bulbs do what when you push the low medium and high buttons.

For example if you create a template light that when set to low activates a scene or script that sets the desired bulbs to the desired brightness along with a delay or transition. the plugin then calls a different scene when you set the template light to medium, etc.
