### ISSUE TITLE
Matching switch entity

### ISSUE THREAD

**Issue by jazzyisj** [finity69x2/light-brightness-preset-row#14]
Have you given any thought to supporting switches with this plugin?

One of these things is not like the others!

![image](https://user-images.githubusercontent.com/44064559/77590298-cde16400-6ec3-11ea-902f-5def9fa966e2.png)

**Comment by finity69x2** [comment]
That's a good idea! And it should be fairly easy.

Thanks!

It will be a few days but I'll let you know when its done.
