### ISSUE TITLE
Custom element doesn't exist: light-brightness-preset-row.

### ISSUE THREAD

**Issue by emruff** [finity69x2/light-brightness-preset-row#15]
After upgrading HA to 107.6 I get the follow error: 

Custom element doesn't exist: light-brightness-preset-row.

entity: light.bedroom_nightstand
type: 'custom:light-brightness-preset-row'
name: Bedroom Lights
customTheme: true
customSetpoints: true
LowBrightness: 1
MedBrightness: 100
HiBrightness: 225

**Comment by finity69x2** [comment]
it works for me just fine on v107.7.

try updating to that version and see if it fixes it.

**Comment by emruff** [comment]
Turns out I had a formatting error in my lovelace yaml. Thanks for responding.
