### ISSUE TITLE
Can we have a flag to turn off the bulb icon ?

### ISSUE THREAD

**Issue by lowema** [finity69x2/light-brightness-preset-row#16]
Hi there
Love this card so much, it helps keep things looking amazing in my dashboards.
Any chance we could have a flag to turn on/off the appearance of the bulb icon ?
I use this card alongside an RGB colour selector and would love to turn the icon off when it's in a rollup or used in combination with other entity cards.
Thanks for all your amazing work !

**Comment by finity69x2** [comment]
No I don't think that would be possible, at least using my code. This card isn't really a "card" it just adds functionality to the state portion of an entity. the icon is controlled by the card that the entity is in.

I don't know if there are any other methods you could use to do that but maybe look into some of the other true custom "cards" that might allow that functionality.

If you find one you should still be able to use my row in the card as long as it allows for the definition of an entity in the card.
