### ISSUE TITLE
feature request: same thing, but for cover entities

### ISSUE THREAD

**Issue by ktownsend-personal** [finity69x2/light-brightness-preset-row#18]
I have distinct positions I always use for my binds. It would be great to have buttons instead of a slider. For both sets of blinds I have 4 positions, but it makes sense to support a configurable number of positions. The position values differ depending on which set of blinds I'm using. For example, my partial setting for the bathroom is 20% for light with privacy, but the blinds on the back of the house are partial at 80% to block the setting sun but still see outside. Full open is usually 50%. I also have 2 different closed positions (up or down) so the housekeeper can dust both sides of the blinds.

**Comment by finity69x2** [comment]
Ok could probably easily do that but it would be a completely different (but similar) card. 

The only issue is I don't have any "percentage open" covers. So i would need to figure out what the commsnds are for that. But it should be doable i think.

**Comment by ktownsend-personal** [comment]
Might this be what you need?

attribute `current_position` ranges from 0 to 100 to see where the blind is positioned (in my case tilt position)

an example service call to set position:
```
    - service: cover.set_cover_position
      data:
        entity_id: cover.master_bath_blind_left
        position: 50       
```

Some blinds need their upper/lower bounds to be 1/99 rather than 0/100 due to "factors". Mine fit that category. 
I think it would be handy to have a specific position each button sets to, but a range of values where the button is considered "on".

**Comment by finity69x2** [comment]
Do you have any suggestions on what the various button texts should be (keeping in mind the size constraints of the buttons)?

I'll keep them configurable as they are now but I'm not sure what the default text should be.

I thought 0% for closed (or open depending on what 0% represents) for the old "off" button and 100% for open (or closed...) for the old "high" button but that implies fixed values for the buttons which doesn't make sense for the middle two buttons (the old "low" & "med" buttons).

I could likely get away with using "open" but "closed" would make the text for that button too big. Maybe "shut" would work. And then what do I call the middle two buttons in that vein? Obviously "almost open" & "almost closed" wouldn't work. ;)

OTOH, I guess I could use whatever the programmed positions are as the button text and just use 0%, 33%, 66% and 100% as the defaults.

And the question that the above implies is - what is the postion for open/closed? Is 0% for open or 0% for closed? and are they always the same for all of those types of covers?

**Comment by ktownsend-personal** [comment]
I agree the button text is challenging. I am currently using close, open, angle, clean for my 4 positions. That may not be appropriate as defaults for many people. In my case, the open position is 50%. The angle position is some other angle depending on which blinds (blocking sun is 80% and blocking for privacy is 12%). I originally had "block" as the label but my wife prefers "angle". The close and clean positions are 0% and 100%. They are both closed, at opposite ends of the travel. I called the alternate closed position "clean" because it's only used when we clean dust from the other side of the blinds.

**Comment by finity69x2** [comment]
Ok, so, I think I have a plan...

I'l set the button text to whatever the positions are programmed to. So if the buttons are set at the default values above then the buttons will have that as the text. If the set positions are modified from default then those will be the new default button text. If the buttons are named differently then those names will override the button text.

Here is what I have gotten done so far:

https://github.com/finity69x2/cover-position-preset-row

I believe it should work ok using all of the custom settings.

Try it out and see what you think.

I'm going to close this issue here so if there are any problems either open an issue in that repo or pm me on the HA forum.

Thanks for the suggestion. This theme is really starting to fill out as a comprehensive set.

**Comment by ktownsend-personal** [comment]
nice! I'm installing it now to check it out.
