### ISSUE TITLE
Adjusting button sizes

### ISSUE THREAD

**Issue by memphisdj** [finity69x2/light-brightness-preset-row#2]
I truly love the card, however will it be possible in a future release (if it is planned) to make the button sizes adjustable. Because it is really small on my Note 9 screen.

Thank you for your consideration.

**Comment by finity69x2** [comment]
I likely won't make any changes to the button sizes. And I especially will likely not make them configurable.

Right now the way they are sized is to make them thematically the same as my fan control row.

and If it would take a bunch of work to make them configurable that I really am hesitant to do. And besides if you use the same lovelace config on different devices and you make the buttons bigger they will be too big for another view.

I can look into it but I can't make any promises.

PR's are welcome tho. :)

**Comment by memphisdj** [comment]
Thank you for the thorough answer. I would love to help, but unfortunetly my skill set is not enough.
I will close the issue.
