### ISSUE TITLE
Feature Request - Use Dimmable Lights as Binary

### ISSUE THREAD

**Issue by TacticalBill** [finity69x2/light-brightness-preset-row#20]
Requesting a way to configure this card to display dimmable lights as only On/Off. I have several switches that are technically dimmers, but I have the ZWave parameters set so that it only operates as On/Off. This addon card seems to only be able to display the switch as a dimmer with Off/Low/Med/High.

**Comment by finity69x2** [comment]
You can use the binary-control-button-row to get the on/off functionality. It works for lights too. Even dimmable ones as long as they use the turn_on & turn_off services to turn them off and on with changing the dim setting.

**Comment by TacticalBill** [comment]
Thank you! I didn't know that existed. Exactly what I was looking for.
