### ISSUE TITLE
Feature Request: Set Light Temperature

### ISSUE THREAD

**Issue by almighty059** [finity69x2/light-brightness-preset-row#25]
I do not see a way to set the light temperature for the presets. Being able to have them turn on at let's say 4500k would be great.

**Comment by finity69x2** [comment]
I'm not sure how I could add another setting that would be accessible via the dashboard to select both the brightness and the color temperature at the same time..

I could add it as an option to always set it to a certain value based on the lovelace config but I don't like that since you would need to edit the config if you ever wanted to change the temperature.

Do you have an idea how it could be implemented using the existing four buttons because I don't think I do at this point?

**Comment by almighty059** [comment]
I am still a novice so forgive me if I explained it wrong or if I am misinterpreting your reply. So when you say "dashboard" do you mean the front end of the actual Lovelace card.? And when you say "lovelace config" do you mean the configuration.yaml file.? If so, then no that is not what I meant. The four buttons on the card are fine. Your card is meant specifically for brightness presets and the simplicity of that is great. I am not trying to change or add to that. I only want to be able to change to brightness with the preset buttons. What I meant was something that could be added via the code editor in the same way that reverseButton is used but it would be color_temp. All three brightness buttons would have a default or predefined color temperature or even RGB color. The user would not be able to change the color temp or RGB color on the frontend of the Lovelace card unless they tap the entity name and bring up the info details like always but there would at least be a default or predefined color that all of the brightness buttons turn on to. I have no knowledge of how backend coding works so I do not know if this is something that could easily be added as an option or not. The way in which this would help would be if I have one light or group of lights and one or all of them get changed to green. If I use your card they go right back to green but at the brightness settings of your card. I would rather have the option to leave it like that or set a default for the color so that I know that when I quickly hit that button I am back to "normal".

**Comment by finity69x2** [comment]
I don't think that will be possible.

the biggest issue is going to be that there are many different light integrations that use different methods of setting the color.

looking at the docs these are all the possible different options:

hs_color
xy_color
rgb_color
rgbw_color
rgbww_color
color_temp
kelvin
color_name

I don't think I can reasonably accommodate all of those myriad options in one plug-in...at least fairly easily. The code would be a huge mess.

I think I will pass on this one. Sorry.
