### ISSUE TITLE
Missing Tile background in black and white them

### ISSUE THREAD

**Issue by Glennesink** [finity69x2/light-brightness-preset-row#26]
![image](https://user-images.githubusercontent.com/83347489/137131455-0705011f-9539-46e1-b6ee-4698d48b5ea6.png)
Hi The background is missing, is this a feature that can be implemented or is it a bug?

**Comment by jazzyisj** [comment]
Can you post your config where you added these entities?  I think you added them as cards instead of entity rows.  They are meant to be contained within a card.

**Comment by Glennesink** [comment]
You are correct Thanks!
