### ISSUE TITLE
Documentation regarding binary lights/switches?

### ISSUE THREAD

**Issue by bobloadmire** [finity69x2/light-brightness-preset-row#27]
I see the binary switch example jpg, but I don't see any sample code showing how a binary switch is added. Any information on this?

**Comment by finity69x2** [comment]
that was an example showing the different plug-ins from my other repositories and how they can be thematically correlated for a consistent look on the dashboard. The one you are referring to is the [binary-control-button-row](https://github.com/finity69x2/binary-control-button-row).

Sorry for the confusion.
