### ISSUE TITLE
hassChanged runs too often

### ISSUE THREAD

**Issue by papadi** [finity69x2/light-brightness-preset-row#29]
I was trying to debug your code, trying to improve it and I noticed that hassChanged callback is called about every 5 seconds. Is this normal?
btw the issue I'm trying to debug is that buttons don't look selected when I use your component for a group item, which has 3 dimmable lights behind it, but this isn't the purpose of this question.

**Comment by finity69x2** [comment]
TBH, I'm not really sure.

I don't see anything in the code that sets the rate at which the service is called so I assume that's handled elsewhere in HA outside of this plugin.

But I'm not really a programmer as such in this respect. I just cobbled some stuff together from other sources and it seemed to work OK.

If you have suggestions to improve things I'll be glad to hear them.

as far as the PR you submitted I'm assuming you've done some testing and it still works for other non-grouped lights as well.

It looks like it should but just checking.

**Comment by papadi** [comment]
On the contrary, I AM a programmer but I've never done any programming on hass. Looking at it again, I noticed that it's not in your control, so I guess it's alright.
