### ISSUE TITLE
Wrong level highlighted 

### ISSUE THREAD

**Issue by mdezzi** [finity69x2/light-brightness-preset-row#3]
I am using this plugin with a Shelly Dimmer and AmazonBasics dimable LED bulbs. For medium and low settings i have to use 175 and 100 respectively. 

It seems that there is a hardcoded feedback that highlights the medium button when the brightness is set to Low. When i click low, the level drops to 100, but the medium button is highlighted. When i click the medium button, the high button is selected. The light does receive the correct brightness value, it just looks like the code that highlights the active setting is hard coded and not relying on the three settings I customized.

**Comment by finity69x2** [comment]
@mdezzi

The three buttons do have a somewhat hard-coded range but the ranges are fairly wide. 

From the docs:

"Low" button (valid range: 0 - 85)
"Med" button (valid range: 86 - 170)
"High" button (valid range: 171 - 255)

depending how you have the config set up if the options are set outside of those ranges for each button the values will default to the appropriate upper or lower limit for the desired button. If you have 175 set for medium then the button preset will limit itself to 170. and 100 is above the upper limit for the low button so it will limit itself to 85.

also I believe that the setting that the light will go to should also be the same limiting values as the buttons.

So if you have 100 for low & 175 for medium then the limits will kick in and low should be 85 & medium should be 170 and that is what the setpoint of the light should go to - if you use the buttons. If you are using anything outside the card (a service or a slider) then you can set it to whatever you want and the correct button will be highlighted dependent on the setpoint selected and the value limited setting of the buttons.

Could you post the code for your button so I can see exactly how you have it and I can test it on my system to try to replicate what you are seeing?

**Comment by mdezzi** [comment]
See below for my code. The buttons work correctly to set the light at the different brightnesses, but when i click medium, the high is highlighted, when i click low, the medium is highlighted. The problem is my light is off from 0 to 100, so my low and medium are higher than expected. 

If you could dynamically set the highlight ranges based on the values given it would probably work much better.  (i.e. low is from 0 to midpoint between low/med, med is from midpoint of low/med to midpoint of med/high and high is above that)

```
entities:
  - HiBrightness: 225
    LowBrightness: 100
    MedBrightness: 175
    customSetpoints: true
    entity: light.fireplace_lights
    type: 'custom:light-brightness-preset-row'
```

**Comment by finity69x2** [comment]
@mdezzi 

I'll look into it to see what I can do. But I'm not sure what that might be.

When I was developing this I had no hard coded limits and ran into overlap/indication issues but I can't remember what exactly the problems were that made me do it the way I did. I'll have to see if I wrote it in my notes.

Your suggestion might work, tho.

**Comment by finity69x2** [comment]
@mdezzi 

Do you know how to load code from the dev branch?

I've got the updated code there right now so if you can test it for me that would be really helpful.

**Comment by mdezzi** [comment]
@finity69x2 just uninstalled the HACS version and manually loaded the dev version. the updated code looks like it is working correctly. thanks!!

**Comment by finity69x2** [comment]
that's good. thanks for testing it for me.

I'll update the HACS repo as soon as I get a chance.

**Comment by finity69x2** [comment]
On HACS now.
