### ISSUE TITLE
Card state does not fully reflect lights groups state

### ISSUE THREAD

**Issue by RayLation** [finity69x2/light-brightness-preset-row#31]
Hello,

I have a group of 2 lights which I control with a light-brightness-preset-row card. If I always use the card to control the lights group, everything works fine. Though if I manually control one of the 2 lights (without using the card), then the card doesn't reflect the state of the lights group. The icon does get lit with the right color, but the Hi/Medium/Low buttons don't lit up and the Off button stays lit but is inactive and cannot be used.

This causes 2 problems:
1-I think the lights are all off when looking at the card
2-Even if I know one of the lights is ON, I cannot turn it off with the card, since the OFF button is lit but DISABLED.

I don't know what should be the right behavior for this, but Home Assistant does not react the same way. If I do the same thing, the group entity state does say ON. 

Thank you!

**Comment by finity69x2** [comment]
Well, that looks like it was an unintended consequence of a PR I approved back in December. :/

Sorry about that. I should have tested it better. But TBH,I don't use light groups so the thought never crossed my mind that the person who submitted the PR was incorrect.

I'll see about reverting that change.

Thank you for pointing it out.

**Comment by finity69x2** [comment]
I just submitted a change to the plugin to revert to the prior functionality.

it should be available in HACS soon.

Please let me know if it fixes it for you.

**Comment by RayLation** [comment]
Hello!

Sorry for late reply, my box was down for several days... :(

Thank you, it (almost) works perfectly now. The issue only remains with lights that are not actual lights. Let me explain: 

Some of my lights are actually switches that I instantied as a light entity like this:

```
lights:
- platform: switch
    name: bureau_backlight
    entity_id: switch.bureau_backlight

```
Those entities can then be controlled as a standard light entity... but they don't have a brightness control:

![image](https://user-images.githubusercontent.com/92007174/173278381-86882800-1e15-4f69-8ee5-4afbc01cc89d.png)


For these, I get the same behavior as my original post... My guess is that your code is based on the brightness only, and not on the on/off state... 

Thanks for your time, I really like and use this. FYI, here's a look at my main dashboard on my mobile:

![image](https://user-images.githubusercontent.com/92007174/173278576-9277b582-3af9-4cc1-a18c-8099f396ae2b.png)

**Comment by finity69x2** [comment]
right.

the plugin is specifically made for changing the brightness of lights. If the lights don't support brightness then this plugin won't work. 

I'm not even sure it would be easily possible (or even make sense) to have different functionality based on different capabilities of the light entities.

sorry, I think that I'm going to close this based on that.
