### ISSUE TITLE
Card doesn't work with group entity

### ISSUE THREAD

**Issue by nexro567** [finity69x2/light-brightness-preset-row#33]
Hi all,

Unfortunately the card stops working with groups.
The off button indicates a status, even if the lights are on. The low, medium and high buttons are functional but does not indicates the status. Switch off button does not work. I have no problems with individual entities.

`type: entities
title: Hall Light Presets
show_header_toggle: false
entities:
   entity: group.eetkamer_verlichting
    type: custom:light-brightness-preset-row
    name: Spots
    icon: mdi:track-light
    reverseButtons: true
    customTheme: true
    customSetpoints: true
    lowBrightness: 64
    medBrightness: 128
    hiBrightness: 255
    state_color: true
    customHiText: STERK
    customLowText: ZACHT
    customMedText: MILD
    customOffText: UIT
    width: 40px
    height: 30px`

**Comment by nexro567** [comment]
`type: entities
title: Hall Light Presets
show_header_toggle: false
entities:
  - entity: group.eetkamer_verlichting
    type: custom:light-brightness-preset-row
    name: Spots
    icon: mdi:track-light
    reverseButtons: true
    customTheme: true
    customSetpoints: true
    lowBrightness: 64
    medBrightness: 128
    hiBrightness: 255
    state_color: true
    customHiText: STERK
    customLowText: ZACHT
    customMedText: MILD
    customOffText: UIT
    width: 40px
    height: 

> 30px`

**Comment by finity69x2** [comment]
are you sure you are on the latest version.

I just tested it and it works as expected for the test group:

![light group test](https://user-images.githubusercontent.com/32221243/175790932-11640db4-1575-43c8-9cfb-2bbe009a61d3.gif)
