### ISSUE TITLE
Add support for more than 3 presets

### ISSUE THREAD

**Issue by mlg9000** [finity69x2/light-brightness-preset-row#34]
I use this card to make my dimmable lamps function as 3-ways in the HA UI.  It would be nice to add another preset (ultra-low in my case) to the UI as well so that I can make them 4-ways instead.

**Comment by finity69x2** [comment]
I get asked this similar question all the time and I always give the same answer...

there needs to be a limitation as to how many buttons there are. I've had people ask for up to 10 buttons before.

I've decided that three buttons plus off is a good compromise between functionality and aesthetics as far as screen space.

So unfortunately I won't be implementing this. sorry.
