### ISSUE TITLE
Customize brightness levels / Color

### ISSUE THREAD

**Issue by aneisch** [finity69x2/light-brightness-preset-row#8]
Would it be possible to expand this plugin to allow the setting of brightness AND color? i.e storing and recalling scenes for light(s). I envision being able to define "day" "evening" and "night" profiles which are combinations of brightness and color, and then being able to click and apply those presets.

**Comment by finity69x2** [comment]
I don't think I want to do that.

The code and the resultant configuration options start getting very large and complex.

And I think that is best done by using scenes.

And just now while writing this I think you could solve your situation by creating automations that set the desired scene based on the brightness setting of the light in the card.

Or you could even create a dummy light using the light template and then you could use the brightness of the dummy light to trigger an automation to set the desired scene.
