### ISSUE TITLE
Multiple Entities?

### ISSUE THREAD

**Issue by aptonline** [finity69x2/light-brightness-preset-row#9]
From the docs I'm not sure but is it possible to assign multiple light entities so in theory you could change an entire room to the same brightness? failing that would it work for groups?

**Comment by finity69x2** [comment]
there is no way to use the card with multiple entities in one card.

I think you could do as I suggested in issue #8 (closed) and create a dummy template light and use the brightness setting of that light to trigger an automation so set the brightness of multiple other lights.

as far as groups are concerned that question was asked in issue #7. I asked the OP a question about the operation of the light groups (I don't use them) a few days ago but they haven't responded yet.

**Comment by aptonline** [comment]
Thanks for the update.
